# Generated by Django 4.2 on 2024-02-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('average_rating', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('review_count', models.IntegerField()),
                ('genres', models.TextField()),
                ('num_pages', models.IntegerField(null=True)),
                ('publish_date', models.DateField()),
                ('goodreads_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
