# Generated by Django 4.2 on 2024-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
