# Generated by Django 4.2 on 2024-02-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_scraper', '0002_alter_book_genres_alter_book_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='goodreads_url',
            field=models.URLField(default='https://www.goodreads.com'),
        ),
    ]
