# Generated by Django 4.2 on 2024-02-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_scraper', '0003_book_goodreads_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='goodreads_url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='BookHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField()),
                ('goodreads_id', models.CharField(max_length=20, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_scraper.book')),
            ],
        ),
    ]
