# Generated by Django 4.2 on 2024-02-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_scraper', '0004_alter_book_goodreads_url_bookhtml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100, null=True)),
                ('likes', models.IntegerField(null=True)),
            ],
        ),
    ]
